name: Deployment

on:
  push:
    branches:
      - develop
      - prod
env:
  develop_branch: "develop"
  prod_branch: "prod"

permissions:
  contents: read
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Copy env variables
        run: |
          cp .deployment/.env-${{ github.ref_name }} .env
      - name: Build
        run: |
          npm run build
      - name: Set deployment target
        id: set-target
        run: |
          if [ "${{ github.ref_name }}" == "${{ env.develop_branch }}" ]; then
            echo "target=develop.globals.one" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "${{ env.prod_branch }}" ]; then
            echo "target=public_html" >> $GITHUB_ENV
          else
            echo "Error: Unsupported branch ${GITHUB_REF_NAME}" >&2
            exit 1
          fi
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GS_CPANEL_SERVER_IP }}
          username: ${{ secrets.GS_CPANEL_SSH_USER }}
          key: ${{ secrets.GS_CPANEL_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.GS_CPANEL_SSH_PRIVATE_KEY_PASSPHRASE }}
          port: 22
          source: "out/*"
          target: ${{ env.target }}
          strip_components: 1
